In [697]:
import numpy as np
import pandas as pd

In [749]:
df = pd.read_csv("Training_Data_0611N.csv", index_col='cust_id', skipfooter=4, engine='python')
ev_df = pd.read_csv("Evaluation_Data_0611_Nv.csv", index_col='cust_id', engine='python')

In [750]:
flag = df['profitable_flag']

In [751]:
train = df.drop(['profitable_flag'],axis=1)
print(train.shape,ev_df.shape)

(19595, 48) (5000, 48)


In [783]:
train_df = pd.concat([train,ev_df])
train_df.shape
print(train_df)

         count_accts  cm_age  flag_top_ed_spender  flag_cust_fee_paid_6m  \
cust_id                                                                    
550391             1      74                  1.0                    0.0   
550392             1      64                  0.0                    0.0   
550393             1      75                  1.0                    0.0   
550394             2      73                  0.0                    1.0   
550395             2      68                  0.0                    0.0   
...              ...     ...                  ...                    ...   
574981             1      36                  1.0                    0.0   
574982             1      35                  1.0                    0.0   
574983             1      28                  0.0                    0.0   
574984             1      34                  0.0                    0.0   
574985             2      40                  1.0                    0.0   

        pre

In [784]:
train_df.columns

Index(['count_accts', 'cm_age', 'flag_top_ed_spender', 'flag_cust_fee_paid_6m',
       'pre6m_cust_spend', 'pre6m_cust_roc_cnt', 'pre6m_cust_non_disc_amt',
       'pre6m_cust_non_disc_cnt', 'pre6m_cust_disc_amt', 'pre6m_cust_disc_cnt',
       'pre6m_cust_outbound_amt', 'pre6m_cust_online_amt',
       'pre6m_cust_online_cnt', 'pre6m_cust_travel_amt',
       'pre6m_cust_travel_cnt', 'pre6m_cust_retail_amt',
       'pre6m_cust_retail_cnt', 'pre6m_cust_myca_active',
       'pre6m_cust_mob_logins', 'pre6m_total_mc_trs', 'acq_sub_chn',
       'acq_type_grp', 'fee_type_grp', 'Cust_tenure', 'pre6m_spend_active_ind',
       'highly_utilized_ind', 'min_pay_ind', 'paid_in_full_ind',
       'sum_total_line_amt', 'direct_debit_ind', 'referrals', 'spillover',
       'self_accts', 'Customer Low Quality indicator', 'cdss_most_rcnt_prob',
       'cust_max_credit_12m_amt', 'cust_max_remit_12m_amt', 'cbr_3_score',
       'cnsumr_chrg_actv_cust_cnt', 'cnsumr_chrg_avg_credit_12m_amt',
       'cnsumr_lend_a

In [785]:
train_df.shape

(24595, 48)

In [786]:
cat_data = [col for col in train_df.columns if train_df[col].dtype == object]
cat_data

['pre6m_cust_spend',
 'pre6m_cust_non_disc_amt',
 'pre6m_cust_disc_amt',
 'pre6m_cust_outbound_amt',
 'pre6m_cust_online_amt',
 'pre6m_cust_travel_amt',
 'pre6m_cust_retail_amt',
 'pre6m_total_mc_trs',
 'acq_sub_chn',
 'acq_type_grp',
 'fee_type_grp',
 'sum_total_line_amt',
 'cust_max_credit_12m_amt',
 'cust_max_remit_12m_amt',
 'cnsumr_chrg_avg_credit_12m_amt',
 'sow_tot_annual_ext_pmt_amt',
 'sow_tot_revol_bal_amt',
 'sow_tot_trans_bal_amt']

In [787]:
train_df['pre6m_cust_spend'].unique()

array([' 1,518 ', ' 4,807 ', ' 2,361 ', ..., ' 9,913 ', ' 9,756 ',
       ' 13,388 '], dtype=object)

In [788]:
for col in cat_data:
    print(col,train_df[col].unique())

pre6m_cust_spend [' 1,518 ' ' 4,807 ' ' 2,361 ' ... ' 9,913 ' ' 9,756 ' ' 13,388 ']
pre6m_cust_non_disc_amt [' 811 ' ' 1,052 ' ' 1,351 ' ... ' 9,571 ' ' 3,760 ' ' 5,293 ']
pre6m_cust_disc_amt [' 707 ' ' 3,756 ' ' 1,010 ' ... ' 9,084 ' ' 8,890 ' ' 1,873 ']
pre6m_cust_outbound_amt [' -   ' ' 673 ' ' 237 ' ... ' 4,962 ' ' 6,607 ' ' 4,183 ']
pre6m_cust_online_amt [' 606 ' ' 3,164 ' ' 693 ' ... ' 11,764 ' ' 6,442 ' ' 6,527 ']
pre6m_cust_travel_amt [' 28 ' ' 2,291 ' ' -   ' ... ' (261)' ' 25,701 ' ' 1,898 ']
pre6m_cust_retail_amt [' 814 ' ' 1,265 ' ' 1,623 ' ... ' 7,151 ' ' 3,975 ' ' 5,670 ']
pre6m_total_mc_trs [' (2)' ' 15 ' ' (20)' ... ' 1,143 ' ' 867 ' ' 518 ']
acq_sub_chn ['Unreferred' 'In House' nan 'Affiliates' 'MGM' 'Email' 'Partner'
 'Non-PDB (Personalized)' 'Outsourced' 'PDB (Personalized)' 'Interactive'
 'Media' 'Search' 'Direct' 'Partnerships - Other'
 'Partnerships - In Store' 'Paid Search' 'Personalization' 'E-mails'
 'E-Mails' 'Natural Referral' 'Proprietary - Direct Sales' 'DM

In [789]:
cat_2 = ['acq_sub_chn','acq_type_grp','fee_type_grp']
cat_data  = [x for x in cat_data if x not in cat_2]
for col in cat_data:
    train_df[col] = train_df[col].str.replace(',', '')
    train_df[col] = train_df[col].str.replace('(', '')
    train_df[col] = train_df[col].str.replace(')', '')
    train_df[col] = train_df[col].str.replace(')', '')
    train_df[col] = train_df[col].str.replace(' ', '')
    train_df[col] = train_df[col].str.replace('-', '0')
    train_df[col] = train_df[col].replace(np.nan, '0')
    train_df[col] = train_df[col].astype(int)
#     train_df[col] = train_df[col].replace('...', np.nan)
# for col in cat_data:
#     print(col,train_df[col].unique())
train_df['pre6m_cust_spend'].unique()

array([ 1518,  4807,  2361, ...,  9913,  9756, 13388])

In [790]:
train_df['fee_type_grp'].isna().sum()

0

In [791]:
# replace field that's entirely space (or empty) with NaN
train_df = train_df.replace(r'^\s*$', np.nan, regex=True)
# print(train_df.replace(r'^\s*$', np.nan, regex=True))
train_df['acq_type_grp'].isna().sum()

1014

In [792]:
sum([True for idx,row in train_df.iterrows() if any(row.isnull())])

1492

In [793]:
train_df['acq_sub_chn'].isna().sum()

1053

In [794]:
missing_cols = [col for col in train_df.columns if train_df[col].isnull().any()]
missing_cols

['flag_top_ed_spender',
 'acq_sub_chn',
 'acq_type_grp',
 'Cust_tenure',
 'pre6m_spend_active_ind',
 'highly_utilized_ind',
 'min_pay_ind',
 'paid_in_full_ind',
 'direct_debit_ind',
 'referrals',
 'spillover',
 'self_accts',
 'Customer Low Quality indicator',
 'cdss_most_rcnt_prob',
 'cbr_3_score',
 'cnsumr_chrg_actv_cust_cnt',
 'cnsumr_lend_actv_cust_cnt',
 'cnsumr_lend_tot_util_ratio',
 'sow_revol_avg_paydown_pct',
 'sow_tot_revol_cnt',
 'sow_tot_trans_cnt']

In [795]:
train_df['acq_sub_chn'].fillna("unknown", inplace = True)
train_df['acq_type_grp'].fillna("unknown", inplace = True)
train_df['fee_type_grp'].fillna("unknown", inplace = True)
missing_cols  = [x for x in missing_cols if x not in ['acq_sub_chn','acq_type_grp',]]
missing_cols

['flag_top_ed_spender',
 'Cust_tenure',
 'pre6m_spend_active_ind',
 'highly_utilized_ind',
 'min_pay_ind',
 'paid_in_full_ind',
 'direct_debit_ind',
 'referrals',
 'spillover',
 'self_accts',
 'Customer Low Quality indicator',
 'cdss_most_rcnt_prob',
 'cbr_3_score',
 'cnsumr_chrg_actv_cust_cnt',
 'cnsumr_lend_actv_cust_cnt',
 'cnsumr_lend_tot_util_ratio',
 'sow_revol_avg_paydown_pct',
 'sow_tot_revol_cnt',
 'sow_tot_trans_cnt']

In [796]:
for col1 in ['flag_top_ed_spender',
             'pre6m_spend_active_ind',
             'highly_utilized_ind',
             'referrals',
             'spillover',
            'self_accts',
            'Customer Low Quality indicator',
            'cnsumr_lend_actv_cust_cnt',
             'direct_debit_ind',
             'cnsumr_chrg_actv_cust_cnt',
             'flag_cust_fee_paid_6m'
            ]:
    train_df[col1].fillna(0, inplace = True)
train_df[ 'sow_revol_avg_paydown_pct'].unique()

array([0.    , 0.0877, 0.0168, ..., 0.2034, 0.2068, 0.1632])

In [797]:
for col1 in ['min_pay_ind',
             'paid_in_full_ind',
    ]:
    train_df[col1].fillna(1, inplace = True)

In [798]:
for col1 in ['cdss_most_rcnt_prob',
             'cbr_3_score',
            'cnsumr_lend_tot_util_ratio',
            'Cust_tenure',
            'sow_revol_avg_paydown_pct', 'sow_tot_revol_cnt', 'sow_tot_trans_cnt','count_accts',
 'cm_age','pre6m_cust_roc_cnt',
 'pre6m_cust_non_disc_cnt',
 'pre6m_cust_disc_cnt',
 'pre6m_cust_online_cnt',
 'pre6m_cust_travel_cnt',
 'pre6m_cust_retail_cnt',
             'pre6m_cust_myca_active',
 'pre6m_cust_mob_logins',
            ]:
#     train_df[col1].fillna(0, inplace = True)
    train_df[col1].fillna((train_df[col1].mean()), inplace = True)

In [799]:
sum([True for idx,row in train_df.iterrows() if any(row.isnull())])
missing_cols = [col for col in train_df.columns if train_df[col].isnull().any()]
missing_cols

[]

In [800]:
train_df['acq_sub_chn'].unique()

array(['Unreferred', 'In House', 'unknown', 'Affiliates', 'MGM', 'Email',
       'Partner', 'Non-PDB (Personalized)', 'Outsourced',
       'PDB (Personalized)', 'Interactive', 'Media', 'Search', 'Direct',
       'Partnerships - Other', 'Partnerships - In Store', 'Paid Search',
       'Personalization', 'E-mails', 'E-Mails', 'Natural Referral',
       'Proprietary - Direct Sales', 'DM', 'Outbound', 'Unaddressed',
       'Natural Search'], dtype=object)

In [801]:
train_df['acq_type_grp'].unique()

array(['external', 'others', 'unknown', 'spillover'], dtype=object)

In [802]:
train_df['fee_type_grp'].unique()

array(['no_fee', 'full_fee', 'reduced_fee', 'unknown'], dtype=object)

In [803]:
from sklearn import preprocessing

In [804]:
le = preprocessing.LabelEncoder()
train_df['acq_type_grp_le']=le.fit_transform(train_df['acq_type_grp'])
train_df['acq_type_grp_le'].unique()

array([0, 1, 3, 2])

In [805]:
train_df['acq_sub_chn_le']=le.fit_transform(train_df['acq_sub_chn'])
train_df['acq_sub_chn_le'].unique()

array([24,  6, 25,  0,  8,  5, 17, 12, 14, 15,  7,  9, 22,  2, 19, 18, 16,
       20,  4,  3, 10, 21,  1, 13, 23, 11])

In [806]:
train_df['fee_type_grp_le']=le.fit_transform(train_df['fee_type_grp'])
train_df['fee_type_grp_le'].unique()

array([1, 0, 2, 3])

In [848]:
# corr = train_df.corr().sort_values('profitable_flag', ascending=False)
train_dfx = train_df.head(19595)
train_dfc = pd.merge( flag,train_df, left_index=True, right_index=True)
# train_df1['profitable_flag'] = df['profitable_flag']

corr = abs(train_dfc.corr()).sort_values('profitable_flag', ascending=False)
corr_col = corr.iloc[:,0].index
print(corr.iloc[:,0])
corr_col[-5:]

profitable_flag                   1.000000
pre6m_cust_spend                  0.122924
pre6m_cust_travel_cnt             0.112781
pre6m_cust_disc_amt               0.112370
pre6m_cust_travel_amt             0.103841
cust_max_remit_12m_amt            0.103686
cust_max_credit_12m_amt           0.103143
pre6m_cust_roc_cnt                0.096348
pre6m_cust_non_disc_amt           0.091580
pre6m_cust_retail_amt             0.090721
pre6m_cust_disc_cnt               0.087323
pre6m_cust_outbound_amt           0.086922
pre6m_cust_online_amt             0.083858
pre6m_cust_non_disc_cnt           0.077625
cnsumr_chrg_avg_credit_12m_amt    0.067118
pre6m_total_mc_trs                0.052265
flag_top_ed_spender               0.045787
pre6m_cust_retail_cnt             0.045425
sum_total_line_amt                0.043872
pre6m_cust_online_cnt             0.043151
pre6m_spend_active_ind            0.043024
spillover                         0.037482
fee_type_grp_le                   0.036341
min_pay_ind

Index(['acq_sub_chn_le', 'pre6m_cust_mob_logins', 'sow_tot_trans_cnt',
       'sow_tot_revol_bal_amt', 'highly_utilized_ind'],
      dtype='object')

In [849]:
# train_df_temp = train_df.drop(['sow_revol_avg_paydown_pct','sow_tot_revol_cnt',
#  'sow_tot_trans_cnt','fee_type_grp','acq_sub_chn','acq_type_grp'], axis = 1)
train_df_temp = train_df.drop(['fee_type_grp','acq_sub_chn','acq_type_grp'], axis = 1)
corr_col  = [x for x in corr_col if x not in ['sow_revol_avg_paydown_pct','sow_tot_revol_cnt',
 'sow_tot_trans_cnt']]
train_df1 = train_df_temp.drop(corr_col[-20:], axis = 1)
train_df1

flag_top_ed_spender  pre6m_cust_spend  pre6m_cust_roc_cnt  \
cust_id                                                              
550391                   1.0              1518                 122   
550392                   0.0              4807                 354   
550393                   1.0              2361                 204   
550394                   0.0              5452                 142   
550395                   0.0               170                  34   
...                      ...               ...                 ...   
574981                   1.0              6635                 160   
574982                   1.0              3384                 612   
574983                   0.0              3611                 620   
574984                   0.0               926                  80   
574985                   1.0              3111                 356   

         pre6m_cust_non_disc_amt  pre6m_cust_non_disc_cnt  \
cust_id                                                     
550391                       811                       96   
550392                      1052                       82   
550393                      1351                      118   
550394                      1195                       50   
550395                        88                       20   
...                          ...                      ...   
574981                      5293                       96   
574982                      2089                      322   
574983                       974                      138   
574984                       290                       38   
574985                      2067                      228   

         pre6m_cust_disc_amt  pre6m_cust_disc_cnt  pre6m_cust_outbound_amt  \
cust_id                                                                      
550391                   707                   26                        0   
550392                  3756                  272                      673   
550393                  1010                   86                      237   
550394                  4257                   92                      803   
550395                    82                   14                       10   
...                      ...                  ...                      ...   
574981                  1342                   64                      421   
574982                  1295                  290                       95   
574983                  2638                  482                     1343   
574984                   635                   42                       19   
574985                  1043                  128                      369   

         pre6m_cust_online_amt  pre6m_cust_online_cnt  ...  spillover  \
cust_id                                                ...              
550391                     606                     36  ...        0.0   
550392                    3164                    456  ...        1.0   
550393                     693                    152  ...        0.0   
550394                    1618                     64  ...        0.0   
550395                      10                      4  ...        0.0   
...                        ...                    ...  ...        ...   
574981                     638                     32  ...        0.0   
574982                     817                    232  ...        0.0   
574983                    1327                    660  ...        0.0   
574984                     198                     48  ...        0.0   
574985                     876                    168  ...        0.0   

         self_accts  cdss_most_rcnt_prob  cust_max_credit_12m_amt  \
cust_id                                                             
550391          0.0             0.000000                      482   
550392          0.0             0.000000                     2165   
550393          0.0             0.000000                      7

In [850]:
y = flag
X = train_df1.head(19595)
y.shape

(19595,)

In [851]:
X.shape

(19595, 28)

In [852]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import average_precision_score

# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5)
# print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)
X_train = X
y_train = y
X_test = train_df1.tail(5000)
print(X_test)

         flag_top_ed_spender  pre6m_cust_spend  pre6m_cust_roc_cnt  \
cust_id                                                              
569986                   0.0              9868                 760   
569987                   0.0                 0                   0   
569988                   1.0              2401                 302   
569989                   1.0              9836                 856   
569990                   0.0              2351                 260   
...                      ...               ...                 ...   
574981                   1.0              6635                 160   
574982                   1.0              3384                 612   
574983                   0.0              3611                 620   
574984                   0.0               926                  80   
574985                   1.0              3111                 356   

         pre6m_cust_non_disc_amt  pre6m_cust_non_disc_cnt  \
cust_id                     

In [853]:
print(X_train.shape, X_test.shape, y_train.shape)

(19595, 28) (5000, 28) (19595,)


In [854]:
from sklearn.ensemble import RandomForestClassifier
# model2 = RandomForestClassifier(max_depth=2, random_state=1)
model = RandomForestClassifier()
model.fit(X_train,y_train)
y_pred = model.predict(X_test)
print(model.score(X_train,y_train))
print(f1_score(y_train, model.predict(X_train), average='macro'))
average_precision_score(y_train, model.predict(X_train))

0.9984179637662669
0.9973798557120019


0.992973137845602

In [855]:
# tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
# recall = tp / (tp + fn)
# prec = tp / (tp + fp)
# F1 = 2 * recall * prec / (recall + prec)
# print(recall, prec, F1)

In [856]:
y_pred.shape
df = X_test.copy()[[]]
df

Empty DataFrame
Columns: []
Index: [569986, 569987, 569988, 569989, 569990, 569991, 569992, 569993, 569994, 569995, 569996, 569997, 569998, 569999, 570000, 570001, 570002, 570003, 570004, 570005, 570006, 570007, 570008, 570009, 570010, 570011, 570012, 570013, 570014, 570015, 570016, 570017, 570018, 570019, 570020, 570021, 570022, 570023, 570024, 570025, 570026, 570027, 570028, 570029, 570030, 570031, 570032, 570033, 570034, 570035, 570036, 570037, 570038, 570039, 570040, 570041, 570042, 570043, 570044, 570045, 570046, 570047, 570048, 570049, 570050, 570051, 570052, 570053, 570054, 570055, 570056, 570057, 570058, 570059, 570060, 570061, 570062, 570063, 570064, 570065, 570066, 570067, 570068, 570069, 570070, 570071, 570072, 570073, 570074, 570075, 570076, 570077, 570078, 570079, 570080, 570081, 570082, 570083, 570084, 570085, ...]

[5000 rows x 0 columns]

In [857]:
final_output =  pd.DataFrame(data=y_pred,columns=['profitable_flag'])
# df['profitable_flag']=final_output
final_output['new_index'] = range(569986, 574986, 1)
final_output

profitable_flag  new_index
0                   1     569986
1                   0     569987
2                   0     569988
3                   0     569989
4                   0     569990
...               ...        ...
4995                0     574981
4996                0     574982
4997                0     574983
4998                0     574984
4999                0     574985

[5000 rows x 2 columns]

In [858]:
out1 = final_output[['new_index','profitable_flag']]
out1.head()
out1.to_csv('prediction.csv',index=False,header=False)